Target:
	gcc change-tripleMatrix-T.c -o change-tripleMatrix-T
	gcc generate-matrix-float.c -o generate-matrix-float
	gcc change-tripleMatrix.c -o change-tripleMatrix 
	gcc generate-matrix-int.c -o generate-matrix-int
